require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '6283890107168',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
   ALIVE_URL: process.env.ALIVE_URL,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUQzVTZ3MGQ0d1k5VHUyc1prVFJkYnd0UlQxa1lHcit2QWw4ejgyeXZGYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieTRQSVNCalloT2RhbW5hQUVMaUdGUWRzVUVoOG8rOVVLMzVhamhoTEx5RT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJlUDhPVHcwTWlXREprMVJSUFZnbzEwa0lzV1VyV0lhODZ6T05Jc0FUdmxNPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJGT2g4YXFLK2FsSkx4bDhYYStuU3FWZVZocTRIbmlUU1J6MXFmMkY4Z1ZnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBIV25Wc0hxdWdDeUs1Y3dIdjRMNGlIMFZXYmMrZXd4Q0VINlNoMnlaazA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InMxazk2M0EyaWJrOHJUaHBRUFhqTitleEFVTHV5ekJ0N2FNdHhkelAvVTg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRUo2SUVZV2RsaEEzU0liS1R5dGZRdlhyRHdUT1lxVFl1d1hES1Y4dkdIQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVzhYY1YrZ3ROMTUvMGN4cEpONUNHZkY2RUJNNXd3a3VKeitoNGs0U0h3cz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik0rTXh2R3BWRHBCdTJ3RUxvalBPSU13b2FtY0lmd0NWeXpPTG00L1NVMllCOXNXSHdoWlUyaDJHaTcvQ3JCZEYrN3NVdTl6YXlOaTBSbkpBbWxaL0FRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODIsImFkdlNlY3JldEtleSI6Im5YSVJROXdUUGdraDlGVEpsT3NNd3pucXdDRytSVmdhQmhwMXJkRGpLUTg9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiNjI4Mzg5MDEwNzE2OEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI5NTdENzg2N0Q1MzJCMTIzNTZCN0ExRDJFQjRGQzI1RCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUxOTUwMzE3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI2MjgzODkwMTA3MTY4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjY2RTY4MkRFNjc5QjgzN0M4Q0NCRTMzQTEyQUVENzMzIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTE5NTAzMTd9LHsia2V5Ijp7InJlbW90ZUppZCI6IjYyODM4OTAxMDcxNjhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiOTE4RUFERjQyQUVFOUI4MTZCNEI1QkUwOTFDMkM3MjMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1MTk1MDMzNX1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiTDMzVlcyRzgiLCJtZSI6eyJpZCI6IjYyODM4OTAxMDcxNjg6OUBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjcwNjA5NzY1NzEyMDA3OjlAbGlkIiwibmFtZSI6IkJ5dGUifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0tiZXF0WUhFTnpIc3NNR0dBSWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Ii90WllLNlV0eHkwLy9yVG5iQXM1dEdTUnJVam5uK0dOa1pOQ3I5ak1sa3c9IiwiYWNjb3VudFNpZ25hdHVyZSI6IkZ2bzdNR2w2SVZ3MzJMdzZLb0pTK0JmNVlIbm8wT3NPNXA0a29laDdhQ2xQRStXc2dGbFBxMXRQbjRqL3BHbk1aMW0rcTYwV1JINDlZeEdVY1VsZUN3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJrQ1V3Q2ppeGZpbmdJbWxEelVxOElOcjRsUEh3azZZZzd0dG9nV05jeUxQOWVLT3JYSHh3ekhmUlowS0phMW5XaGtiVVlvN1NTZkIzN0E2NWliMFpDQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjYyODM4OTAxMDcxNjg6OUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJmN1dXQ3VsTGNjdFAvNjA1MndMT2JSa2thMUk1NS9oalpHVFFxL1l6SlpNIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQVVJRFE9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTE5NTAzMTMsImxhc3RQcm9wSGFzaCI6IjFLNGhINCIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSHY0In0=',
    timezone: 'Africa/Nairobi',
    USER_LID: process.env.YOUR_LID || 706097657120079,
    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
